### ISSUE TITLE
tablet mode switch is not available as a hardware sensor

### ISSUE THREAD

**Issue by csp5me** [sonnyp/linux-minibook-x#12]
The tablet mode switch to lock keyboard and touchpad by Gnome or KDE will never work as the tablet mode switch sensor is not available in the Chuwi device.

It works in Windows because Windows driver only needs accelerometer sensor.

```
> sudo libinput list-devices | grep Device
Device:           Video Bus
Device:           Lid Switch
Device:           Power Button
Device:           Sleep Button
Device:           GXTP7386:00 27C6:0118 Stylus
Device:           GXTP7386:00 27C6:0118 Keyboard
Device:           GXTP7386:00 27C6:0118
Device:           XXXX0000:04 093A:0255 Mouse
Device:           XXXX0000:04 093A:0255 Touchpad
Device:           Intel HID events
Device:           Intel HID 5 button array
Device:           AT Translated Set 2 keyboard

```
On devices with a working tablet mode switch you get these output:

```
❯ sudo dmesg | grep Tablet
[    1.497034] input: Tablet Mode Switch as /devices/LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:03/PNP0C09:00/GOOG0006:00/input/input3

❯ sudo libinput debug-events | egrep -e Tablet\|SWITCH
-event2   DEVICE_ADDED            Tablet Mode Switch                seat0 default group2  cap:S
-event2   SWITCH_TOGGLE           +0.000s	switch tablet-mode state 1
 event2   SWITCH_TOGGLE           +27.140s	switch tablet-mode state 0
 event2   SWITCH_TOGGLE           +36.730s	switch tablet-mode state 1
 event2   SWITCH_TOGGLE           +47.700s	switch tablet-mode state 0

```

**Comment by sonnyp** [comment]
it's not because the device is not listed that it isn't physically there. That's the point of hardware enablement. 

I don't think you are correct and I don't see how an hardware accelerometer can be used as reliable tablet mode switch.

**Comment by sonnyp** [comment]
https://github.com/lschans/chuwi-tablet confirms there is a hardware  tablet mode switch sensor

EDIT: looks like it's using a combination of 2 accelerometers 

let's keep the conversation at https://github.com/sonnyp/linux-minibook-x/issues/5
