### ISSUE TITLE
MDA6655 -> use MXC4005 kernel driver

### ISSUE THREAD

**Issue by nexero** [sonnyp/linux-minibook-x#2]
Hey @sonnyp, 

after patching the /kernel/drivers/iio/accel/mxc4005.c kernel module, the accelerometer does work properly :)
I just added `MDA6655` and `mda6655` to the `*-device-id`-structs and compiled and loaded the module via DKMS.

Maybe that's some valuable info for you and other Linux users, too.

Cheers!

**Comment by nexero** [comment]
FYI: someone did submit the patch already to the Linux Kernel, and it is available from 6.9-rc1 on. So when 6.9 gets released, everything should be just fine!

**Comment by sonnyp** [comment]
That's awesome, thanks for letting us know.

Next step is tablet mode switch, I haven't had much luck yet but kernel and hardware enablement isn't exactly my specialty.

Perhaps you'll get more lucky ? https://github.com/sonnyp/linux-minibook-x?tab=readme-ov-file#tablet-switch
