### ISSUE TITLE
Keyboard + Trackpad Not Working

### ISSUE THREAD

**Issue by maxexcloo** [sonnyp/linux-minibook-x#9]
Curious if anyone else has had this issue - when using newer kernels (within the last few weeks on OpenSUSE or Fedora).

May be related: https://github.com/linux-surface/linux-surface/issues/1437

**Comment by sleeply4cat** [comment]
I have no much data, but probably related to keyboard locking acpi bug.
try
```
modprobe acpi_call
echo '\_SB.ACMK.LTSM 0' > /proc/acpi/call
```

**Comment by maxexcloo** [comment]
> I have no much data, but probably related to keyboard locking acpi bug. try
> 
> ```
> modprobe acpi_call
> echo '\_SB.ACMK.LTSM 0' > /proc/acpi/call
> ```

Is this a new issue? Will give it a shot now!

**Comment by sleeply4cat** [comment]
It seems like some bios versions or hardware revisions don't initialise keyboard lock status properly, and sometimes after reboot/sleep it locks spontaneously. So general issue is about INT33D3 sensor again lol.
It occurred like 3 times on my device from the very start, so I had no chance to test if triggering locking mechanism actually fixes it, but visually it matches the locked state.

**Comment by maxexcloo** [comment]
Powering down and then booting again fixed it, very odd issue tbh
